# Generated by Django 3.1.12 on 2025-12-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('article', models.CharField(default='00000031425', max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('composition', models.TextField()),
            ],
        ),
    ]
