# Generated by Django 3.1.12 on 2026-01-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tshirts', 'Футболки'), ('hoodies', 'Худі'), ('shoppers', 'Шопери'), ('hats', 'Шапки')], default='tshirts', max_length=20),
        ),
    ]
