# Generated by Django 3.1.12 on 2026-01-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productcolor_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Артикул'),
        ),
    ]
