# Generated by Django 3.1.12 on 2026-01-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20260127_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Артикул'),
        ),
    ]
