# Generated by Django 3.1.12 on 2026-01-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20260127_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, default=0, max_length=10, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
    ]
