# Generated by Django 3.1.12 on 2026-02-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_profilemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Оплата при отриманні'), ('card', 'Карткою на сайті')], default='cash', max_length=20, verbose_name='Спосіб оплати'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Оплата при отриманні'), ('card', 'Карткою на сайті')], default='cash', max_length=20, verbose_name='Спосіб оплати за замовчуванням'),
        ),
    ]
