# Generated by Django 6.0.2 on 2026-04-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_id_alter_orderitem_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(choices=[('black', 'Чорний'), ('white', 'Білий'), ('grey', 'Сірий'), ('blue', 'Синій'), ('red', 'Червоний')], max_length=20),
        ),
    ]
